# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

__all__ = [
    "InvalidJsonError",
    "JsonDepthError",
    "Validator",
]

class InvalidJsonError(ValueError): ...
class JsonDepthError(ValueError): ...

@typing.final
class Validator:
    def __new__(
        cls,
        max_param_length: builtins.int,
        dangerous_patterns: typing.Sequence[builtins.str],
        allowed_roots: typing.Sequence[builtins.str] = [],
        max_path_depth: builtins.int = 1024,
        max_json_depth: builtins.int = 1024,
    ) -> Validator: ...
    def validate_json_data(self, data: typing.Any) -> typing.Optional[tuple[builtins.str, builtins.str]]: ...
    def validate_json_bytes(self, raw_body: bytes) -> typing.Optional[tuple[builtins.str, builtins.str]]: ...
    def validate_parameters(self, parameters: typing.Sequence[tuple[builtins.str, builtins.str]]) -> typing.Optional[tuple[builtins.str, builtins.str]]: ...
    def validate_resource_path(self, path: builtins.str) -> builtins.str: ...
    def sanitize_response_body(self, body: bytes) -> bytes: ...
