apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcpgateway.fullname" . }}
  labels:
    app: {{ include "mcpgateway.name" . }}
    chart: {{ include "mcpgateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.env.PORT | default 4444 | int }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "mcpgateway.name" . }}
    release: {{ .Release.Name }}
