sudo: false
language: python
python:
  - 3.11
services:
  - docker
os:
  - linux
before_install:
  - rm -f ~/.netrc
  - sudo cat /etc/apt/sources.list; sudo ls /etc/apt/sources.list.d/
  - sudo sed -i '/erlang/s/^/#/' /etc/apt/sources.list.d/*.list
  - sudo apt-get -qq update || true
  - sudo apt-get install -y aspell aspell-en || true
  - make venv
  - source ${HOME}/.venv/mcpgateway/bin/activate
  - pip install .[dev]
jobs:
  include:
    - stage: build
      script:
        - make lint | tee docs/docs/test/lint.md
    - stage: build
      script:
        - docker build -f Containerfile --platform=linux/amd64 -t mcpgateway/mcpgateway .
        - docker images
        - docker run --name mcpgateway -p 4444:4444 -d mcpgateway/mcpgateway
        - docker ps -a && sleep 10
        - curl -X POST http://localhost:4444/servers -u admin:changeme
        - docker logs mcpgateway
git:
  depth: false
