{{/* -------------------------------------------------------------------
     DEPLOYMENT — Redis
     -------------------------------------------------------------------
     • Name + labels templated with <release>-mcp-stack-redis.
     • Keeps a single replica; if you need HA, swap for a StatefulSet
       or an external Redis cluster.
     ------------------------------------------------------------------- */}}

{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-stack.fullname" . }}-redis
  labels:
    {{- include "mcp-stack.labels" . | nindent 4 }}
    app: {{ include "mcp-stack.fullname" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mcp-stack.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "mcp-stack.fullname" . }}-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
          {{- with .Values.redis.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
