{{- if .Values.mcpContextForge.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mcp-stack.fullname" . }}-ingress
  annotations:
    {{- range $key, $value := .Values.mcpContextForge.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.mcpContextForge.ingress.className }}
  rules:
    - host: {{ .Values.mcpContextForge.ingress.host }}
      http:
        paths:
          - path: {{ .Values.mcpContextForge.ingress.path }}
            pathType: {{ .Values.mcpContextForge.ingress.pathType }}
            backend:
              service:
                name: {{ include "mcp-stack.fullname" . }}-mcpgateway
                port:
                  number: {{ .Values.mcpContextForge.service.port }}
          {{- if and .Values.mcpFastTimeServer.enabled .Values.mcpFastTimeServer.ingress.enabled }}
          - path: {{ .Values.mcpFastTimeServer.ingress.path }}
            pathType: {{ .Values.mcpFastTimeServer.ingress.pathType }}
            backend:
              service:
                name: mcp-fast-time-server
                port:
                  number: {{ .Values.mcpFastTimeServer.ingress.servicePort }}
          {{- end }}
{{- end }}
