apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  user: {{ .Values.postgres.credentials.user | quote }}
  password: {{ .Values.postgres.credentials.password | quote }}
