{{/* -------------------------------------------------------------------
     SECRET - Gateway Sensitive Configuration
     -------------------------------------------------------------------
     - Renders a Secret named   <release>-mcp-stack-gateway-secret
     - Keys come from values.yaml → mcpContextForge.secret
     - Uses stringData so you can keep readable values in your values.yaml;
       Kubernetes will base64-encode them on creation.
     - Put ONLY sensitive credentials or tokens here.
     ------------------------------------------------------------------- */}}
{{- if .Values.mcpContextForge.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-stack.fullname" . }}-gateway-secret
  labels:
    {{- include "mcp-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
type: Opaque
data:
  BASIC_AUTH_USER: {{ default "admin" .Values.mcpContextForge.secret.data.BASIC_AUTH_USER | b64enc }}
  BASIC_AUTH_PASSWORD: {{- if or .Values.mcpContextForge.secret.regeneratePassword (not .Values.mcpContextForge.secret.data.BASIC_AUTH_PASSWORD) }}
    {{ randAlphaNum 32 | b64enc }}
  {{- else }}
    {{ .Values.mcpContextForge.secret.data.BASIC_AUTH_PASSWORD | b64enc }}
  {{- end }}
  JWT_SECRET_KEY: {{ .Values.mcpContextForge.secret.data.JWT_SECRET_KEY | b64enc }}
  AUTH_ENCRYPTION_SECRET: {{ .Values.mcpContextForge.secret.data.AUTH_ENCRYPTION_SECRET | b64enc }}
{{- end }}
