# templates/secret-postgres.yaml
{{- if and .Values.postgres.enabled (not .Values.postgres.pgSecretMounts) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "mcp-stack.postgresSecretName" . | trim }}"
type: Opaque
stringData:
  # add the keys the Postgres image needs
  POSTGRES_USER: {{ .Values.postgres.credentials.user | quote }}
  POSTGRES_PASSWORD:  {{ .Values.postgres.credentials.password  | quote }}
{{- else if  and .Values.postgres.generatePostgresqlPasswordSecret.enabled (not .Values.postgres.enabled ) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "mcp-stack.postgresSecretName" . | trim }}"
type: Opaque
stringData:
  # add the keys the Postgres image needs
  POSTGRES_USER: {{ .Values.postgres.generatePostgresqlPasswordSecret.postgresqlUsername  | quote }}
  POSTGRES_PASSWORD:  {{ .Values.postgres.generatePostgresqlPasswordSecret.postgresqlPassword  | quote }}
{{- end }}
