{{- if and .Values.pgbouncer.enabled .Values.pgbouncer.useConfigFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-stack.fullname" . }}-pgbouncer-auth
  labels:
    {{- include "mcp-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  userlist.txt: |
    "{{ .Values.postgres.credentials.user | default "admin" }}" "{{ .Values.postgres.credentials.password | default "" }}"
{{- end }}
