"""Add password expiration fields to EmailUser

Revision ID: 3a4ae2025159
Revises: z1a2b3c4d5e6
Create Date: 2025-11-27 13:57:38.604342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4ae2025159'
down_revision: Union[str, Sequence[str], None] = 'z1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_users', sa.Column('password_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('email_users', sa.Column('password_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('email_users', sa.Column('expiry_notification_sent', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###
    
    # Initialize password expiration dates for existing users
    from datetime import datetime, timezone, timedelta
    
    # Get the current timestamp
    now = datetime.now(timezone.utc)
    # Set password creation to now and expiration to 90 days from now
    password_expires_at = now + timedelta(days=90)
    
    # Update existing users to set their password created and expires timestamps
    op.execute(f"""
        UPDATE email_users 
        SET password_created_at = '{now.isoformat()}',
            password_expires_at = '{password_expires_at.isoformat()}',
            expiry_notification_sent = false
        WHERE password_created_at IS NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_users', 'expiry_notification_sent')
    op.drop_column('email_users', 'password_expires_at')
    op.drop_column('email_users', 'password_created_at')
    # ### end Alembic commands ###
