"""add_source_scanner_tables

Revision ID: 7cf3942e5f5c
Revises: f1a2b3c4d5e6
Create Date: 2026-03-04 15:08:46.166765

"""

# Standard
from typing import Sequence, Union

# Third-Party
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7cf3942e5f5c"
down_revision: Union[str, Sequence[str], None] = "f1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_finding_severity"), table_name="source_scanner_findings")
    op.drop_index(op.f("ix_source_scanner_findings_dedup_key"), table_name="source_scanner_findings")
    op.drop_index(op.f("ix_source_scanner_findings_id"), table_name="source_scanner_findings")
    op.drop_index(op.f("ix_source_scanner_findings_scan_id"), table_name="source_scanner_findings")
    op.drop_index(op.f("ix_source_scanner_findings_severity"), table_name="source_scanner_findings")
    op.drop_table("source_scanner_findings")
    op.drop_index(op.f("idx_scan_commit_created"), table_name="source_scanner_scans")
    op.drop_index(op.f("idx_scan_repo_created"), table_name="source_scanner_scans")
    op.drop_index(op.f("ix_source_scanner_scans_commit_sha"), table_name="source_scanner_scans")
    op.drop_index(op.f("ix_source_scanner_scans_created_at"), table_name="source_scanner_scans")
    op.drop_index(op.f("ix_source_scanner_scans_id"), table_name="source_scanner_scans")
    op.drop_index(op.f("ix_source_scanner_scans_repo_url"), table_name="source_scanner_scans")
    op.drop_table("source_scanner_scans")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_scanner_scans",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("repo_url", sa.VARCHAR(length=2048), nullable=False),
        sa.Column("ref", sa.VARCHAR(length=256), nullable=True),
        sa.Column("commit_sha", sa.VARCHAR(length=64), nullable=True),
        sa.Column("languages", sa.VARCHAR(length=1024), nullable=True),
        sa.Column("blocked", sa.BOOLEAN(), nullable=False),
        sa.Column("block_reason", sa.TEXT(), nullable=True),
        sa.Column("error_count", sa.INTEGER(), nullable=False),
        sa.Column("warning_count", sa.INTEGER(), nullable=False),
        sa.Column("info_count", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_scanner_scans")),
    )
    op.create_index(op.f("ix_source_scanner_scans_repo_url"), "source_scanner_scans", ["repo_url"], unique=False)
    op.create_index(op.f("ix_source_scanner_scans_id"), "source_scanner_scans", ["id"], unique=False)
    op.create_index(op.f("ix_source_scanner_scans_created_at"), "source_scanner_scans", ["created_at"], unique=False)
    op.create_index(op.f("ix_source_scanner_scans_commit_sha"), "source_scanner_scans", ["commit_sha"], unique=False)
    op.create_index(op.f("idx_scan_repo_created"), "source_scanner_scans", ["repo_url", "created_at"], unique=False)
    op.create_index(op.f("idx_scan_commit_created"), "source_scanner_scans", ["commit_sha", "created_at"], unique=False)
    op.create_table(
        "source_scanner_findings",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("scan_id", sa.INTEGER(), nullable=False),
        sa.Column("scanner", sa.VARCHAR(length=64), nullable=False),
        sa.Column("severity", sa.VARCHAR(length=16), nullable=False),
        sa.Column("rule_id", sa.VARCHAR(length=256), nullable=False),
        sa.Column("message", sa.TEXT(), nullable=False),
        sa.Column("file_path", sa.VARCHAR(length=2048), nullable=True),
        sa.Column("line", sa.INTEGER(), nullable=True),
        sa.Column("column", sa.INTEGER(), nullable=True),
        sa.Column("code_snippet", sa.TEXT(), nullable=True),
        sa.Column("help_url", sa.VARCHAR(length=2048), nullable=True),
        sa.Column("dedup_key", sa.VARCHAR(length=512), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["source_scanner_scans.id"], name=op.f("fk_source_scanner_findings_scan_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_scanner_findings")),
        sa.UniqueConstraint("scan_id", "dedup_key", name=op.f("uq_finding_scan_dedup")),
    )
    op.create_index(op.f("ix_source_scanner_findings_severity"), "source_scanner_findings", ["severity"], unique=False)
    op.create_index(op.f("ix_source_scanner_findings_scan_id"), "source_scanner_findings", ["scan_id"], unique=False)
    op.create_index(op.f("ix_source_scanner_findings_id"), "source_scanner_findings", ["id"], unique=False)
    op.create_index(op.f("ix_source_scanner_findings_dedup_key"), "source_scanner_findings", ["dedup_key"], unique=False)
    op.create_index(op.f("idx_finding_severity"), "source_scanner_findings", ["severity"], unique=False)
    # ### end Alembic commands ###
