"""add image signing tables

Revision ID: 9b680492ec77
Revises: 2612ebdfb9f0
Create Date: 2026-03-10 11:19:33.607695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b680492ec77'
down_revision: Union[str, Sequence[str], None] = '2612ebdfb9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_signing_trusted_signers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('signer_type', sa.String(length=20), nullable=False),
    sa.Column('oidc_issuer', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('subject_regex', sa.String(length=255), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('kms_key_ref', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trusted_signer_enabled', 'image_signing_trusted_signers', ['enabled'], unique=False)
    op.create_index('idx_trusted_signer_issuer', 'image_signing_trusted_signers', ['oidc_issuer'], unique=False)
    op.create_index('idx_trusted_signer_type', 'image_signing_trusted_signers', ['signer_type'], unique=False)
    op.create_table('image_signing_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=True),
    sa.Column('image_ref', sa.String(length=500), nullable=False),
    sa.Column('image_digest', sa.String(length=100), nullable=True),
    sa.Column('signature_found', sa.Boolean(), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=True),
    sa.Column('signer_identity', sa.String(length=255), nullable=True),
    sa.Column('signer_issuer', sa.String(length=255), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rekor_verified', sa.Boolean(), nullable=True),
    sa.Column('slsa_level', sa.Integer(), nullable=True),
    sa.Column('slsa_builder', sa.String(length=255), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('verification_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_verification_assessment', 'image_signing_verifications', ['assessment_id', 'created_at'], unique=False)
    op.create_index('idx_verification_image_ref', 'image_signing_verifications', ['image_ref'], unique=False)
    op.create_index(op.f('ix_image_signing_verifications_assessment_id'), 'image_signing_verifications', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_image_signing_verifications_created_at'), 'image_signing_verifications', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_signing_verifications_created_at'), table_name='image_signing_verifications')
    op.drop_index(op.f('ix_image_signing_verifications_assessment_id'), table_name='image_signing_verifications')
    op.drop_index('idx_verification_image_ref', table_name='image_signing_verifications')
    op.drop_index('idx_verification_assessment', table_name='image_signing_verifications')
    op.drop_table('image_signing_verifications')
    op.drop_index('idx_trusted_signer_type', table_name='image_signing_trusted_signers')
    op.drop_index('idx_trusted_signer_issuer', table_name='image_signing_trusted_signers')
    op.drop_index('idx_trusted_signer_enabled', table_name='image_signing_trusted_signers')
    op.drop_table('image_signing_trusted_signers')
    # ### end Alembic commands ###
