"""unique const changes for prompt and resource

Revision ID: e5a59c16e041
Revises: 9c99ec6872ed
Create Date: 2025-10-15 11:20:53.888488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a59c16e041'
down_revision: Union[str, Sequence[str], None] = '9c99ec6872ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply schema changes to add or update unique constraints for prompts, resources and a2a agents.
    This migration recreates tables with updated unique constraints and preserves data.
    Compatible with SQLite, MySQL, and PostgreSQL.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch_alter_table for SQLite compatibility
    # a2a_agents: drop unnamed UNIQUE (name) and UNIQUE (slug) if they exist, then create named constraint
    with op.batch_alter_table('a2a_agents', schema=None) as batch_op:
        unique_constraints = inspector.get_unique_constraints('a2a_agents')
        for c in unique_constraints:
            if c['column_names'] == ['name'] and not c['name']:
                batch_op.drop_constraint(None, type_='unique', columns=['name'])
            if c['column_names'] == ['slug'] and not c['name']:
                batch_op.drop_constraint(None, type_='unique', columns=['slug'])
        batch_op.create_unique_constraint('uq_team_owner_slug_a2a_agent', ['team_id', 'owner_email', 'slug'])

    # prompts: drop unnamed UNIQUE (name) if it exists, then create named constraint
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        unique_constraints = inspector.get_unique_constraints('prompts')
        for c in unique_constraints:
            if c['column_names'] == ['name'] and not c['name']:
                batch_op.drop_constraint(None, type_='unique', columns=['name'])
        batch_op.create_unique_constraint('uq_team_owner_name_prompt', ['team_id', 'owner_email', 'name'])

    # resources: drop unnamed UNIQUE (uri) if it exists, then create named constraint
    with op.batch_alter_table('resources', schema=None) as batch_op:
        unique_constraints = inspector.get_unique_constraints('resources')
        for c in unique_constraints:
            if c['column_names'] == ['uri'] and not c['name']:
                batch_op.drop_constraint(None, type_='unique', columns=['uri'])
        batch_op.create_unique_constraint('uq_team_owner_uri_resource', ['team_id', 'owner_email', 'uri'])


def downgrade() -> None:
    """
    Revert schema changes, restoring previous unique constraints for prompts, resources and a2a_agents.
    This migration recreates tables with the original unique constraints and preserves data.
    Compatible with SQLite, MySQL, and PostgreSQL.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Use batch_alter_table for SQLite compatibility and check for constraint existence before dropping
    def constraint_exists(table, constraint_name):
        constraints = inspector.get_unique_constraints(table)
        return any(c['name'] == constraint_name for c in constraints)

    # a2a_agents: revert to unamed UNIQUE (name), UNIQUE (slug)
    with op.batch_alter_table('a2a_agents', schema=None) as batch_op:
        if constraint_exists('a2a_agents', 'uq_team_owner_slug_a2a_agent'):
            batch_op.drop_constraint('uq_team_owner_slug_a2a_agent', type_='unique')
            batch_op.create_unique_constraint(None, ['name'])  # unnamed UNIQUE (name)
            batch_op.create_unique_constraint(None, ['slug'])  # unnamed UNIQUE (slug)

    # prompts: revert to UNIQUE (uri), UNIQUE (name) (unnamed)
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        if constraint_exists('prompts', 'uq_team_owner_name_prompt'):
            batch_op.drop_constraint('uq_team_owner_name_prompt', type_='unique')
            batch_op.create_unique_constraint(None, ['name'])  # unnamed UNIQUE (name)
    
    # resources: revert to no unique constraint on (team_id, owner_email, uri)
    with op.batch_alter_table('resources', schema=None) as batch_op:
        if constraint_exists('resources', 'uq_team_owner_uri_resource'):
            batch_op.drop_constraint('uq_team_owner_uri_resource', type_='unique')
            batch_op.create_unique_constraint(None, ['uri'])  # unnamed UNIQUE (uri)
