/**
* Main build script for the HelpDatabase.
* Scans the UI, generates the automatic database, combines it with the manual database,
* then saves it to a final file to be used by the UI runtime.
*/

import fs from "fs";
import path from "path";
import { scan } from "./help-coverage-check.js";
import { generateHelpDatabase } from "./helpDatabaseAutoGenerator.js";

import { ManualHelpDatabase } from "../contextualHelp.js";


const UI_DIR = path.join(process.cwd(), "mcpgateway/admin_ui");


function filterOnlyAutoGenerated(autoDb, manualDb) {
  const filtered = {};
  for (const [key, entry] of Object.entries(autoDb)) {
    // Keep if NOT in manualDb
    if (!manualDb.hasOwnProperty(key)) {
      filtered[key] = entry;
    }
  }
  return filtered;
}


async function buildHelpDatabase() {
  try{
    const uiFieldsSet = scan(UI_DIR);
    const uiFields = Array.from(uiFieldsSet);

    console.log(`🟢 Found ${uiFields.length} câmpuri UI.`);

    const fullCombinedDb = generateHelpDatabase(uiFields, ManualHelpDatabase);
    const autoDbOnly = filterOnlyAutoGenerated(fullCombinedDb, ManualHelpDatabase);
   
    for (const key in autoDbOnly) {
      if (autoDbOnly.hasOwnProperty(key)) {
        autoDbOnly[key].autoGenerated = true;
      }
    }

    const outputPath = path.join(process.cwd(), "mcpgateway", "admin_ui", "helpDatabase.generated_only.json");
    const dirPath = path.dirname(outputPath);

    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
      console.log(`Folder created: ${dirPath}`);
    } else {
      console.log(`The folder already exists: ${dirPath}`);
    }

    try {
      fs.writeFileSync(outputPath, JSON.stringify(autoDbOnly, null, 2), "utf-8");
      console.log("✅ Automatically generated database (without duplicates) saved in:", outputPath);
      console.log("The write completed successfully at: ", outputPath);

    } catch (error) {
      console.error("❌ Error writing file:", error);
    }
    console.log("✅ Automatically generated database (without duplicates) saved in:", outputPath);
  } catch (err) {
    console.error("❌ Error generating HelpDatabase:", err);
  }
}

buildHelpDatabase();

export { buildHelpDatabase };
