/**
* Automatic HelpDatabase entry generator based on list of UI fields.
* Uses suggested text templates by domain, fills in from identifiers.
*/

const templates = {
  server: "Enter the value for the '{feature}' of the server.",
  auth: "Fill in the '{feature}' required for authentication.",
  gateway: "Configure the '{feature}' for the Gateway.",
  a2a: "Set the '{feature}' option for Agent-to-Agent.",
  tool: "Specify the value for '{feature}' in the tool.",
  prompt: "Complete the '{feature}' for the prompt.",
  resource: "Detail the '{feature}' for the resource.",
  misc: "Fill in the '{feature}'.",
};

/**
* Generates a context help object for a uiId.
* @param {string} uiId - UI field id
* @returns {object} - Automatic HelpDatabase entry
*/
export function generateHelpEntry(uiId) {
  const parts = uiId.toLowerCase().split("-");
  const domains = Object.keys(templates);
  const domain = parts.find(p => domains.includes(p)) || "misc";

  const domainIndex = parts.indexOf(domain);
  let featureParts = domainIndex !== -1 ? parts.slice(domainIndex + 1) : parts;
  if (featureParts.length === 0) featureParts = ["required value"];

  const feature = featureParts.join(" ").replace(/-/g, " ");

  const tooltip = templates[domain].replace("{feature}", feature);
  const inlineHint = tooltip + " (example: actual value)";
  const helpIconText = tooltip + " For more details, see the documentation.";
  const docLink = `https://docs.example.com/${domain}/${featureParts.join("-")}`;

  return {
    tooltip,
    inlineHint,
    helpIcon: {
      text: helpIconText,
      docLink
    },
    autoGenerated: true
  };
}


/**
* Combines the automatic database with the manual database, prioritizing the manual one.
* @param {object} autoDb
* @param {object} manualDb
* @returns {object} combined databases
*/
export function mergeHelpDatabases(autoDb, manualDb) {
  const merged = { ...autoDb };

  for (const key in manualDb) {
    if (manualDb.hasOwnProperty(key)) {
      merged[key] = { ...manualDb[key], autoGenerated: false };
    }
  }

  return merged;
}


/**
* Generates full combined HelpDatabase from uiFields.
* @param {string[]} uiFields - list of UI field IDs
* @param {object} manualDb - imported manual database
* @returns {object} combined Help database
*/
export function generateHelpDatabase(uiFields, manualDb) {
  const autoDb = {};
  for (const uiId of uiFields) {
    autoDb[uiId] = generateHelpEntry(uiId);
  }
  return mergeHelpDatabases(autoDb, manualDb);
}
