/**
 * Main generator script for the HelpDatabase.
 * Scans the UI, generates the automatic help entries database,
 * merges it with the manual help entries database,
 * then saves the result as a JS module file to be used by the UI runtime.
 */

import fs from "fs";
import path from "path";
import { scan } from "./help-coverage-check.js";
import { generateHelpDatabase } from "./helpDatabaseAutoGenerator.js";

import { ManualHelpDatabase } from "../contextualHelp.js";

const UI_DIR = path.join(process.cwd(), "mcpgateway/admin_ui");

function filterOnlyAutoGenerated(autoDb, manualDb) {
  const filtered = {};
  for (const [key, entry] of Object.entries(autoDb)) {
    if (!manualDb.hasOwnProperty(key)) {
      filtered[key] = entry;
    }
  }
  return filtered;
}

async function generateHelpDatabaseModule() {
  try {
    const uiFieldsSet = scan(UI_DIR);
    const uiFields = Array.from(uiFieldsSet);

    console.log(`Found ${uiFields.length} UI fields.`);

    const fullCombinedDb = generateHelpDatabase(uiFields, ManualHelpDatabase);
    const autoDbOnly = filterOnlyAutoGenerated(fullCombinedDb, ManualHelpDatabase);

    // Mark automatic entries explicitly
    for (const key in autoDbOnly) {
      if (autoDbOnly.hasOwnProperty(key)) {
        autoDbOnly[key].autoGenerated = true;
      }
    }

    // Output file path (JavaScript module)
    const outputPath = path.join(process.cwd(), "mcpgateway", "admin_ui", "helpDatabase.generated.js");
    const dirPath = path.dirname(outputPath);

    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
      console.log(`Folder created: ${dirPath}`);
    } else {
      console.log(`Folder already exists: ${dirPath}`);
    }

    // Prepare JS module content
    const fileContent = `/**
 * Auto-generated HelpDatabase module.
 * Generated on: ${new Date().toISOString()}
 * Do NOT edit manually; changes will be overwritten.
 */

export const HelpDatabase = ${JSON.stringify(autoDbOnly, null, 2)};
`;

    // Write JS module file
    fs.writeFileSync(outputPath, fileContent, "utf-8");
    console.log(`✅ Generated JS HelpDatabase saved at: ${outputPath}`);

  } catch (err) {
    console.error("❌ Error generating HelpDatabase module:", err);
  }
}

// Run immediately
generateHelpDatabaseModule();

// Export for reuse if needed
export { generateHelpDatabaseModule };
