# ===============================================================
# 🕸️  Web Lint & Static Analysis - Frontend Code Quality Gate
# ===============================================================
# Authors: Mihai Criveti
#   - runs each web linter in its own matrix job for visibility
#   - mirrors the actual CLI commands used locally (no `make`)
#   - ensures fast-failure isolation: one failure doesn't hide others
#   - uses existing package.json dependencies
#   - logs are grouped and plain-text for readability
# ---------------------------------------------------------------

name: Web Lint & Static Analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint-web:
    strategy:
      fail-fast: false
      matrix:
        include:
          # -------------------------------------------------------
          # 🧼 HTML/CSS/JS Linters & Validators
          # -------------------------------------------------------
          - id: htmlhint
            cmd: |
              npx htmlhint "mcpgateway/templates/**/*.html"

          - id: stylelint
            cmd: |
              npx stylelint "mcpgateway/static/**/*.css"

          - id: eslint
            cmd: |
              npx eslint "mcpgateway/static/**/*.js"

          # -------------------------------------------------------
          # 🔒 Security Scanners
          # -------------------------------------------------------
          - id: retire
            cmd: |
              npx retire --path mcpgateway/static

          - id: npm-audit
            cmd: |
              npm audit --audit-level=high || true

          # -------------------------------------------------------
          # 🔍 Additional Code Quality Tools
          # -------------------------------------------------------
          - id: jshint
            cmd: |
              if [ -f .jshintrc ]; then
                npx jshint --config .jshintrc "mcpgateway/static/**/*.js"
              else
                npx jshint --esversion=11 "mcpgateway/static/**/*.js"
              fi

          - id: jscpd
            cmd: |
              npx jscpd "mcpgateway/static/" "mcpgateway/templates/"

          - id: markuplint
            cmd: |
              npx markuplint mcpgateway/templates/*

    name: ${{ matrix.id }}
    runs-on: ubuntu-latest

    steps:
      # -----------------------------------------------------------
      # 0️⃣  Checkout
      # -----------------------------------------------------------
      - name: ⬇️  Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # -----------------------------------------------------------
      # 1️⃣  Node.js Setup
      # -----------------------------------------------------------
      - name: 📦  Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # -----------------------------------------------------------
      # 2️⃣  Install ALL dependencies from package.json
      # -----------------------------------------------------------
      - name: 📦  Install project dependencies
        run: |
          npm ci --legacy-peer-deps || npm install --legacy-peer-deps

      # -----------------------------------------------------------
      # 3️⃣  Install additional tool if not in package.json
      # -----------------------------------------------------------
      - name: 🔧  Install additional tools
        run: |
          # Check and install tools not in package.json
          if ! npm list htmlhint >/dev/null 2>&1; then
            npm install --legacy-peer-deps --no-save htmlhint
          fi
          if ! npm list retire >/dev/null 2>&1; then
            npm install --legacy-peer-deps --no-save retire
          fi
          if ! npm list jshint >/dev/null 2>&1; then
            npm install --legacy-peer-deps --no-save jshint
          fi
          if ! npm list jscpd >/dev/null 2>&1; then
            npm install --legacy-peer-deps --no-save jscpd
          fi
          if ! npm list markuplint >/dev/null 2>&1; then
            npm install --legacy-peer-deps --no-save markuplint
          fi1; then
            npm install --no-save jshint
          fi
          if ! npm list jscpd >/dev/null 2>&1; then
            npm install --no-save jscpd
          fi
          if ! npm list markuplint >/dev/null 2>&1; then
            npm install --no-save markuplint
          fi

      # -----------------------------------------------------------
      # 3️⃣  Run Linter / Validator
      # -----------------------------------------------------------
      - name: 🔍  Run ${{ matrix.id }}
        run: ${{ matrix.cmd }}

  # -------------------------------------------------------
  # 🐍 Python-based JS Security Scanner (separate job)
  # -------------------------------------------------------
  nodejsscan:
    name: nodejsscan
    runs-on: ubuntu-latest

    steps:
      # -----------------------------------------------------------
      # 0️⃣  Checkout
      # -----------------------------------------------------------
      - name: ⬇️  Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # -----------------------------------------------------------
      # 1️⃣  Python Setup
      # -----------------------------------------------------------
      - name: 🐍  Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      # -----------------------------------------------------------
      # 2️⃣  Install nodejsscan
      # -----------------------------------------------------------
      - name: 🔧  Install nodejsscan
        run: |
          python3 -m pip install --upgrade pip
          pip install nodejsscan

      # -----------------------------------------------------------
      # 3️⃣  Run nodejsscan
      # -----------------------------------------------------------
      - name: 🔒  Run nodejsscan
        run: |
          nodejsscan --directory ./mcpgateway/static
